### PR TITLE
fix(): fixes issue #73

### PR DESCRIPTION
**Pull request by jgw96**
#### Short description of what this resolves:

This fixes the roboto and noto-sans fonts not getting included. The copy task did not copy over the fonts before and instead just copied over ionicons. It now copies over fonts and ionicons. This also changes the sass config to make sure it looks in the right directory.
#### Changes proposed in this pull request:
- Change copy.config to pull in all fonts instead of just ionicons
- Change sass.config to look in the right directory

**Fixes**: #73

### CODE REVIEW

**Comment by brandyscarney** [comment]
The only issue with this is it makes the ionicon version dependent on the ionic-angular version. I believe @adamdbradley wanted them separated so if we were to release a new version of ionicons we wouldn't have to release a new version of the framework to go with it.

**Comment by jgw96** [comment]
@brandyscarney yep we are talking about that now. The issue here is that `ionic-angular/fonts` includes ionicons. So i removed the line that includes ionicons explicitly because they are already included in `ionic-angular/fonts`.

**Comment by jgw96** [comment]
Dont merge yet, may have found an issue

**Comment by joshgarwood** [comment]
Hey guys!  Any updates on when this bad boy can be merged in?  My CTO is really wanting our Roboto font back :)

**Comment by brandyscarney** [comment]
@jgw96 Why was the ionicons copy from `node_modules` removed? Updating ionicons is still dependent on the framework's version of ionicons if we copy the fonts from the framework's font folder. I'm thinking we need to remove ionicons from `dist/` in the framework altogether.

**Comment by jgw96** [comment]
The above commit makes sure that the ionicons are copied from ionicons and not the framework. Since the ionicons are copied from `ionicons` first they will not be overwritten by the ones in` ionic-angular/fonts`. Ideally in the future we would remove ionicons from the framework to keep them totally seperate from the framework, but this would be a breaking change.

**Comment by brandyscarney** [comment]
I'm good with this PR, let's get @adamdbradley or @danbucholtz to approve it.

**Pull request merged**
