### PR TITLE
feat(lint): option to disable ts lint and process.exit(1) on error

### PR DESCRIPTION
**Pull request by alan-agius4**
#### Short description of what this resolves:
Add 2 options, one to disable TS lint when running a command and secondly to fail a CI build with process.exit(1);

#### Changes proposed in this pull request:

- Add flag to disable ts lint
- Add config option to exit process with error code 1

More info in the read me file

**Fixes**: #223 #287

### CODE REVIEW

**Comment by ramonornela** [comment]
some notice to merges? this feature is important to used with git hooks @danbucholtz can review

thanks

**Comment by kleeb** [comment]
would be a nice to have feature!

**Comment by marcorosi** [comment]
@kleeb have you tried "--enableLint false"?

see here for more info: https://github.com/ionic-team/ionic-app-scripts#overriding-config-values

**Comment by kleeb** [comment]
Thanks @marcorosi ! That was it

**Comment by kleeb** [comment]
however `--enableLint false` is currently doing exactly the same as `--noLint`

**Comment by yelhouti** [comment]
This is not working for me: ionic cordova build browser --prod --enableLint false
any ideas?

**Comment by yxliang01** [comment]
`--enableLint false` is not working with the latest version of ionic here as well...

**Comment by sextos3** [comment]
Same here, any updates for this?

**Pull request closed without merging**
