### PR TITLE
html-webpack-plugin no longer works with this optimization

### PR DESCRIPTION
**Pull request by superkew**
#### Short description of what this resolves:
Breaking webpack plugins
**Fixes**: #
See https://github.com/driftyco/ionic-app-scripts/issues/903

### CODE REVIEW

**Comment by superkew** [comment]
You can refer to this commit where the code was originally added.
https://github.com/driftyco/ionic-app-scripts/commit/09e11399e1beebbf8be810fadde0e8a5be49feaf

**Comment by danbucholtz** [comment]
Sorry, we added this line intentionally. You may need to rethink the use of that plugin.

Thanks,
Dan

**Comment by superkew** [comment]
I'd gladly use something else if there is another options for cachebusting. Do you know of another way to push the file name of the outpu js into the index.html at compile time?

**Comment by superkew** [comment]
From what I understand the htmlWebpackPlugin simply looks at webpack's output file chunks and hooks into them. It looks like this line of code somehow clears out the output chunks.

**Comment by whtevn** [comment]
I use this plugin is for cachebusting on browser releases. I have been using this successfully, and to great benefit, until this change. It is disappointing that these ionic scripts have to step on webpack so hard that plugins which are more commonly used than ionic itself (79k for htmlwebpack yesterday vs 66k for ionic yesterday by npm numbers) no longer work. 

I really hope you can find a way to prevent breaking this extremely popular and incredibly useful plugin. The workarounds from this breaking change are ugly and create unnecessary maintenance issues.

**Comment by superkew** [comment]
I found a workaround for the browser builds.
In my build I import the ionic webpack.config and then I add the plugin by pushing it to the plugins array. I've now added a line of code that removes the ionic environment plugin first, so that the web build uses the default webpack environment and it builds correctly for me (so far).

```
var baseConfig = require('../node_modules/@ionic/app-scripts/config/webpack.config.js');
var HtmlWebpackPlugin = require('html-webpack-plugin');

baseConfig.plugins.splice(0, 1); // remove ionic-environment-plugin https://github.com/driftyco/ionic-app-scripts/issues/903
baseConfig.plugins.push(new HtmlWebpackPlugin({ ...
```

**Comment by superkew** [comment]
Except it looks like the ionic-env plugin does minification...

**Pull request closed without merging**
