### PR TITLE
Add script to generate changelog

### LINKED ISSUE #8: Automate Changelog
The commits are already in the angular change log format.

It quite trivial to add it to the release process.

Since this is a beta project and internal to the IONIC cli its hard to keep track what changes and doc's are limited, so a change log can help a lot.

Thanks!

### PR DESCRIPTION
**Pull request by shlomiassaf**
@adamdbradley This is implements #8

However, I didn't go far since I don't know your release process. I don't know if it's gulp you prefer or bash scripts... CI automation etc...

This the simplest form, you still need to git tag otherwise it won't have a checkpoint.

I'v created git tags on my fork to represent version 0.0.8 to 0.0.11

Here's are the commands so you can save some time searching:
`git tag -a 0.0.8 7b83647 -m "version 0.0.8"`
`git tag -a 0.0.9 1a5559e -m "version 0.0.9"`
`git tag -a 0.0.10 70883de -m "version 0.0.10"`
`git tag -a 0.0.11 5c6737a -m "version 0.0.11"`

closes #8

### CODE REVIEW

**Comment by shlomiassaf** [comment]
Change log output:

<a name="0.0.11"></a>
## [0.0.11](https://github.com/driftyco/ionic-app-scripts/compare/0.0.10...0.0.11) (2016-09-21)


### Bug Fixes

* **tsc:** fix tsc within watch command ([370fa45](https://github.com/driftyco/ionic-app-scripts/commit/370fa45))


### Features

* **rollup:** cache previous bundles ([f52498f](https://github.com/driftyco/ionic-app-scripts/commit/f52498f))
* **sass:** skip sass rendering when files unchanged ([31f5fef](https://github.com/driftyco/ionic-app-scripts/commit/31f5fef))



<a name="0.0.10"></a>
## [0.0.10](https://github.com/driftyco/ionic-app-scripts/compare/0.0.9...0.0.10) (2016-09-21)


### Bug Fixes

* **watch:** watch tmp js files and remove ngcUpdate ([21e6904](https://github.com/driftyco/ionic-app-scripts/commit/21e6904))



<a name="0.0.9"></a>
## [0.0.9](https://github.com/driftyco/ionic-app-scripts/compare/0.0.8...0.0.9) (2016-09-20)


### Bug Fixes

* **rollup:** remove import of rollupNG2 plugin ([#10](https://github.com/driftyco/ionic-app-scripts/issues/10)) ([75c8aa9](https://github.com/driftyco/ionic-app-scripts/commit/75c8aa9))
* **rollup:** target browser by default ([1a21489](https://github.com/driftyco/ionic-app-scripts/commit/1a21489)), closes [#7](https://github.com/driftyco/ionic-app-scripts/issues/7)
* **sass:** correct user sass variable file paths on windows ([088b736](https://github.com/driftyco/ionic-app-scripts/commit/088b736)), closes [#6](https://github.com/driftyco/ionic-app-scripts/issues/6)



<a name="0.0.8"></a>
## [0.0.8](https://github.com/driftyco/ionic-app-scripts/compare/80f1223...0.0.8) (2016-09-20)


### Bug Fixes

* add support for dev and prod builds ([b992eec](https://github.com/driftyco/ionic-app-scripts/commit/b992eec))
* component sass compiler ([e1aaeb9](https://github.com/driftyco/ionic-app-scripts/commit/e1aaeb9))
* **config:** update config arg and env paths to look at rootDir ([7b83647](https://github.com/driftyco/ionic-app-scripts/commit/7b83647)), closes [#5](https://github.com/driftyco/ionic-app-scripts/issues/5)
* **copy:** add forward slash on asset folder copy config ([#2](https://github.com/driftyco/ionic-app-scripts/issues/2)) ([1a5eb75](https://github.com/driftyco/ionic-app-scripts/commit/1a5eb75))


### Features

* add debug mode and logging ([80f1223](https://github.com/driftyco/ionic-app-scripts/commit/80f1223))
* add watch ([f157603](https://github.com/driftyco/ionic-app-scripts/commit/f157603))
* get config values from npm package.json config ([26bcd28](https://github.com/driftyco/ionic-app-scripts/commit/26bcd28))

**Comment by mlynch** [comment]
Thanks, we're focusing on some other bigger issues so will be reviewing this more slowly. We appreciate the contribution and will follow up next weekish.

**Comment by shlomiassaf** [comment]
@mlynch Totally agree, I would cancel this PR and create change log support within a complete build/release process. 

Did this per request and as a helper to understand changes.

**Comment by adamdbradley** [comment]
I like this, but could we build out a few more scripts with this so it's easier to run?

**Comment by shlomiassaf** [comment]
@adamdbradley Usually, in my setup's, I have a process before a release.
The simplest form is something like:
  - Update changelog
  - Bump version
  - Commit changelog and bump
  - create & commit tag

from there it's usually creating the dist.

I deliberately made it super simple because these setups can be manages in several ways... gulp, npm scripts, bash etc... (I use gulp)

Since i'm not aware of how you manage internal release processes I chose to do it as simple as possible.

**Comment by danbucholtz** [comment]
Manually merged this.

Thanks,
Dan

**Pull request closed without merging**
