### PR TITLE
fix(build): fix issue that `extends` in `ts-config.json` property is …

### PR DESCRIPTION
**Pull request by alan-agius4**
#### Short description of what this resolves:
While typescript support `extends` of another tsconfig, a limitation in `validateRequiredFilesExist` method doesn't as it's reading the file using `fs`, rather than `getTsConfig` which is a wrapper of the `TypeScript API`, 

#### Changes proposed in this pull request:
- Impalement `getTsConfigAsync`  method
- In `validateRequiredFilesExist` use it rather than `readFileAsync` for the `tsconfig.json`

Note: I cannot run Unit Tests

**Fixes**: #745

### CODE REVIEW

**Comment by alan-agius4** [comment]
Bdw, you be good to enable CircleCI to run on PRs

**Comment by alan-agius4** [comment]
@danbucholtz any updates?

**Comment by danbucholtz** [comment]
@alan-agius4,

Can you rebase and submit again? At first glance I would think this would be fine.

Thanks,
Dan

**Comment by alan-agius4** [comment]
@danbucholtz, just did :)

**Comment by danbucholtz** [comment]
screen shot 2017-04-17 at 1 52 09 pm

I see this. Can you fix? I'll test and merge. Please make sure tests pass as well. I updated so they _should_ 🐱 pass on Windows.

Thanks,
Dan

**Comment by alan-agius4** [comment]
screen shot 2017-04-17 at 20 53 50

;/

**Comment by alan-agius4** [comment]
I'll have a look at testing as well

**Comment by alan-agius4** [comment]
unit tests all green :)

**Comment by alan-agius4** [comment]
@danbucholtz all tests arw green and rebased.

**Comment by danbucholtz** [comment]
@alan-agius4,

Can you just resubmit this? Github is not letting me merge still.

Thanks,
Dan

**Comment by alan-agius4** [comment]
@danbucholtz, here's the new PR #910

**Comment by danbucholtz** [comment]
Thanks, I'll test and merge tomorrow.

Thanks,
Dan

**Pull request closed without merging**
