### PR TITLE
Feature/transpile custom compiler options

### PR DESCRIPTION
**Pull request by alan-agius4**
#### Short description of what this resolves:
Provide way for user to provide their own CompilerOptions

#### Changes proposed in this pull request:

- Add transpile config

**Fixes**: #333

### CODE REVIEW

**Comment by danbucholtz** [comment]
@alan-agius4, nice job, can you rebase this and resolve the conflicts?

Thanks,
Dan

**Comment by adamdbradley** [comment]
Can you explain more on why we need another config versus using typescript config?

**Comment by alan-agius4** [comment]
Hi @adamdbradley, it actually merges with your tsconfig. The main reason behind this that some checks that the tsc is doing while transpiling might not be needed why not being in prod mode. 

Such as 'noLibCheck'. By having this one disabled for dev, the tsc doesn't have to validate the the typyings of a 3rd party lib for typings errors and it this it will improve build speeds. That said, for prod, you may still want to valid those and be more strict!

Another option would be something like the 'ionic_source_map' config.

And I don't really know what others users may want to do in dev vs prod.

**Comment by adamdbradley** [comment]
Ok, I see what you mean. I guess my main concern is if this is making config more confusing, like when you would set the transpile config and when you'd change your tsconfig, and what's the difference. How can we add this feature, yet make it crystal clear how and when to use it?

**Comment by alan-agius4** [comment]
Hi Adam,

I think i depends if you want to give the option to the change this
property only or not.

I would have 2 other options;

1) add a command argument flag (--skipLibCheck or inverted --doLibCheck)
depends on what you guys deem should he the default.

2) Add an npm config key. Similar to the bundler sourcemap value.

**Comment by Barryrowe** [comment]
@adamdbradley Another key reason to allow this is for unit tests. You want the tsconfig to include all of your typescript files so your editor will properly validate them, but when building, you don't want your spec files to be included.  As it stands now, I'm having to modify the transpile.js distributed with ionic-app-scripts to exclude my specs and mocks.

**Comment by danbucholtz** [comment]
Sorry, I don't think we want to go ahead with this approach.

Thanks for contributing!

Thanks,
Dan

**Pull request closed without merging**
